# Generated by Django 5.2.8 on 2025-11-13 21:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='კატეგორიის სახელი')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(max_length=500, verbose_name='აღწერა')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images/', verbose_name='ბანერის სურათი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიურია')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=30, verbose_name='გვარი')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='ტელეფონის ნომერი')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='მისამართი')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='დაბადების თარიღი')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'მომხმარებელი',
                'verbose_name_plural': 'მომხმარებლები',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
            ],
            options={
                'verbose_name': 'კალათა',
                'verbose_name_plural': 'კალათები',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='8A26F8F4F5', max_length=32, unique=True, verbose_name='შეკვეთის უნიკალური ნომერი')),
                ('status', models.CharField(choices=[('PENDING', 'დასამუშავებელი'), ('PROCESSING', 'მუშავდება'), ('SHIPPED', 'გაგზავნილია'), ('DELIVERED', 'მიწოდებულია'), ('CANCELLED', 'გაუქმებულია')], default='PENDING', max_length=15, verbose_name='სტატუსი')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ჯამური თანხა')),
                ('shipping_address', models.CharField(max_length=255, verbose_name='მიწოდების მისამართი')),
                ('phone', models.CharField(max_length=15, verbose_name='საკონტაქტო ტელეფონი')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='შენიშვნები')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
            ],
            options={
                'verbose_name': 'შეკვეთა',
                'verbose_name_plural': 'შეკვეთები',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='პროდუქტის სახელი')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='პროდუქტის Slug')),
                ('description', models.TextField(verbose_name='დეტალური აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='მარაგის რაოდენობა')),
                ('is_available', models.BooleanField(default=True, verbose_name='ხელმისაწვდომობა')),
                ('featured', models.BooleanField(default=False, verbose_name='გამორჩეული პროდუქტი')),
                ('color', models.CharField(choices=[('WHITE', 'თეთრი'), ('BLACK', 'შავი'), ('BROWN', 'ყავისფერი'), ('GREY', 'ნაცრისფერი'), ('BEIGE', 'ბეჟი')], max_length=10, verbose_name='ფერი')),
                ('material', models.CharField(choices=[('WOOD', 'ხე'), ('METAL', 'ლითონი'), ('GLASS', 'მინა'), ('LEATHER', 'ტყავი'), ('TEXTILE', 'ტექსტილი'), ('PLASTIC', 'პლასტიკი')], max_length=10, verbose_name='მასალა')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name': 'პროდუქტი',
                'verbose_name_plural': 'პროდუქტები',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='რაოდენობა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი ერთეულზე')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='შეკვეთა')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='პროდუქტი')),
            ],
            options={
                'verbose_name': 'შეკვეთის ერთეული',
                'verbose_name_plural': 'შეკვეთის ერთეულები',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='დამატებითი სურათი')),
                ('is_main', models.BooleanField(default=False, verbose_name='მთავარი სურათი')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='პროდუქტი')),
            ],
            options={
                'verbose_name': 'პროდუქტის სურათი',
                'verbose_name_plural': 'პროდუქტის სურათები',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='რაოდენობა')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='კალათა')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='პროდუქტი')),
            ],
            options={
                'verbose_name': 'კალათის ერთეული',
                'verbose_name_plural': 'კალათის ერთეულები',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
