# Generated by Django 5.2.8 on 2025-11-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='A0BBDB7B6C', max_length=32, unique=True, verbose_name='შეკვეთის უნიკალური ნომერი'),
        ),
    ]
