# Generated by Django 5.2.8 on 2025-11-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='6B0A681527', max_length=32, unique=True, verbose_name='შეკვეთის უნიკალური ნომერი'),
        ),
    ]
