# Generated by Django 5.2.8 on 2025-11-14 02:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_create_initial_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='F7417F495F', max_length=32, unique=True, verbose_name='შეკვეთის უნიკალური ნომერი'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ფასი ერთეულზე'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='რაოდენობა'),
        ),
    ]
