# Generated by Django 5.2.8 on 2025-11-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_order_number_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='5DB151ED62', max_length=32, unique=True, verbose_name='შეკვეთის უნიკალური ნომერი'),
        ),
    ]
